export default [
  {
    fieldId: 1,
    value: 'First Name',
    extraFields: null,
    tableName: 'User',
    columnName: 'firstName',
  },
  {
    fieldId: 1,
    value: 'Last Name',
    extraFields: null,
    tableName: 'User',
    columnName: 'lastName',
  },
  {
    fieldId: 1,
    value: 'Location',
    extraFields: null,
    tableName: 'User',
    columnName: 'address',
  },
  {
    fieldId: 1,
    value: 'Manager’s Name',
    extraFields: null,
    tableName: 'User',
    columnName: 'userName',
  },
  {
    fieldId: 1,
    value: 'Manager’s Email',
    extraFields: null,
    tableName: 'User',
    columnName: 'email',
  },
  {
    fieldId: 1,
    value: 'Email Address',
    extraFields: null,
    tableName: 'User',
    columnName: 'email',
  },
  { fieldId: 2, value: 'Must', extraFields: null },
  { fieldId: 2, value: 'Must Not', extraFields: null },
  { fieldId: 3, value: 'Equal', extraFields: null },
  { fieldId: 3, value: 'Contains', extraFields: null },
  { fieldId: 3, value: 'Starts With', extraFields: null },
  { fieldId: 3, value: 'Ends With', extraFields: null },
  { fieldId: 5, value: 'Must', extraFields: null },
  { fieldId: 5, value: 'Must Not', extraFields: null },
  { fieldId: 6, value: 'Created', extraFields: null },
  { fieldId: 6, value: 'Last Login', extraFields: null },
  { fieldId: 6, value: 'Employee Start Date', extraFields: null },
  { fieldId: 6, value: 'Custom Date 1', extraFields: null },
  { fieldId: 6, value: 'Last Password Change', extraFields: null },
  {
    fieldId: 7,
    value: 'Range',
    extraFields:
      '[{"Type": "TextBox", "fieldName": "Start Date"}, {"Type": "TextBox", "fieldName": "End Date"}]',
  },
  {
    fieldId: 7,
    value: 'Duration',
    extraFields:
      '[{"type": "Select", "values": [{"key": "In the last", "value": "In the last"}, {"key": "Prior to Last", "value": "Prior to Last"}], "fieldName": ""}, {"type": "Select", "values": [{"key": "Month", "value": "Month"}, {"key": "Week", "value": "Week"}, {"key": "Days", "value": "Days"}], "fieldName": ""}]',
  },
  { fieldId: 7, value: 'Any', extraFields: null },
  { fieldId: 8, value: 'Must', extraFields: null },
  { fieldId: 8, value: 'Must Not', extraFields: null },
  { fieldId: 9, value: 'Failed Phishing Test', extraFields: null },
  { fieldId: 9, value: 'Passed Phishing Test', extraFields: null },
  { fieldId: 9, value: 'Any Failures', extraFields: null },
  { fieldId: 9, value: 'Any Failures but Clicks', extraFields: null },
  { fieldId: 9, value: 'Clicked', extraFields: null },
  { fieldId: 9, value: 'Replied', extraFields: null },
  { fieldId: 9, value: 'Open Attachment', extraFields: null },
  { fieldId: 9, value: 'Opened', extraFields: null },
  { fieldId: 10, value: 'Equal', extraFields: null },
  { fieldId: 10, value: 'Greater Than', extraFields: null },
  { fieldId: 10, value: 'Less Than', extraFields: null },
  {
    fieldId: 11,
    value: 'Range',
    extraFields:
      '[{"Type": "TextBox", "fieldName": "Start Date"}, {"Type": "TextBox", "fieldName": "End Date"}]',
  },
  {
    fieldId: 11,
    value: 'Duration',
    extraFields:
      '[{"type": "Select", "values": [{"key": "In the last", "value": "In the last"}, {"key": "Prior to Last", "value": "Prior to Last"}], "fieldName": ""}, {"type": "Select", "values": [{"key": "Month", "value": "Month"}, {"key": "Week", "value": "Week"}, {"key": "Days", "value": "Days"}], "fieldName": ""}]',
  },
  { fieldId: 11, value: 'Any', extraFields: null },
  { fieldId: 13, value: 'Must', extraFields: null },
  { fieldId: 13, value: 'Must Not', extraFields: null },
  { fieldId: 14, value: 'Enrolled', extraFields: null },
  { fieldId: 14, value: 'Started', extraFields: null },
  { fieldId: 14, value: 'Completed', extraFields: null },
  { fieldId: 15, value: 'Any Selected', extraFields: null },
  { fieldId: 15, value: 'All Selected', extraFields: null },
  { fieldId: 15, value: 'Any Available', extraFields: null },
  { fieldId: 16, value: 'need to call api', extraFields: null },
  {
    fieldId: 17,
    value: 'Range',
    extraFields:
      '[{"Type": "TextBox", "fieldName": "Start Date"}, {"Type": "TextBox", "fieldName": "End Date"}]',
  },
  {
    fieldId: 17,
    value: 'Duration',
    extraFields:
      '[{"type": "Select", "values": [{"key": "In the last", "value": "In the last"}, {"key": "Prior to Last", "value": "Prior to Last"}], "fieldName": ""}, {"type": "Select", "values": [{"key": "Month", "value": "Month"}, {"key": "Week", "value": "Week"}, {"key": "Days", "value": "Days"}], "fieldName": ""}]',
  },
  { fieldId: 17, value: 'Any', extraFields: null },
];
